"""empty message

Revision ID: 08f843b6f9aa
Revises: bbcf7428b309
Create Date: 2022-01-19 17:08:29.274325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f843b6f9aa'
down_revision = 'bbcf7428b309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
