"""empty message

Revision ID: 53225c7ccf20
Revises: 08f843b6f9aa
Create Date: 2022-01-19 17:14:18.614426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53225c7ccf20'
down_revision = '08f843b6f9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
