"""empty message

Revision ID: 9f1bc5b26e48
Revises: 53225c7ccf20
Create Date: 2022-01-19 17:14:47.595295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1bc5b26e48'
down_revision = '53225c7ccf20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.Text(), server_default='https://bagheera-img.s3.amazonaws.com/another%40example.com/download.jpeg', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
