"""empty message

Revision ID: ae38f95912aa
Revises: 36873164beaf
Create Date: 2022-01-19 17:02:20.894841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae38f95912aa'
down_revision = '36873164beaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
