"""empty message

Revision ID: bbcf7428b309
Revises: ae38f95912aa
Create Date: 2022-01-19 17:04:51.147309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcf7428b309'
down_revision = 'ae38f95912aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
